//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pritner3D
{
    using System;
    using System.Collections.Generic;
    
    public partial class input_composition
    {
        public string idInput { get; set; }
        public string idComplementInput { get; set; }
        public Nullable<int> quantity { get; set; }
    }
}
